### ISSUE TITLE
unexpected keyword argument 'ssl_verify' error

### ISSUE THREAD

**Issue by callMe-Root** [octodns/octodns-powerdns#46]
Hello, I've been using this module for a long time and I appreciate your work. Recently, our security team is badgering about applying ssl to our powerdns servers. So I went ahead, put an nginx in front of it and set acl to accept only nginx requests. 

For octodns-sync config I followed the documentation, port number changed to 443, scheme is now https and I use fqdn instead of ip address. Everything looks perfect but somehow I couldn't make it verify my ssl certificate, so I tried to use "ssl_verify: false" in configuration to give it a shot but I got this error:

```
(env) root@test-server:/opt/octodns# octodns-sync --config-file=config/test.yaml
octodns-sync --config-file=config/test.yaml
2023-08-28T19:05:40  [139999840723392] INFO  Manager __init__: config_file=config/test.yaml (octoDNS 0.9.21)
2023-08-28T19:05:40  [139999840723392] INFO  Manager _config_executor: max_workers=4
2023-08-28T19:05:40  [139999840723392] INFO  Manager _config_include_meta: include_meta=False
2023-08-28T19:05:40  [139999840723392] INFO  Manager __init__: global_processors=[]
2023-08-28T19:05:40  [139999840723392] ERROR Manager Invalid provider config
Traceback (most recent call last):
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns/manager.py", line 193, in _config_providers
    providers[provider_name] = _class(provider_name, **kwargs)
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns_powerdns/__init__.py", line 640, in __init__
    super().__init__(
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns_powerdns/__init__.py", line 67, in __init__
    super().__init__(id, *args, **kwargs)
TypeError: BaseProvider.__init__() got an unexpected keyword argument 'ssl_verify'
Traceback (most recent call last):
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns/manager.py", line 193, in _config_providers
    providers[provider_name] = _class(provider_name, **kwargs)
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns_powerdns/__init__.py", line 640, in __init__
    super().__init__(
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns_powerdns/__init__.py", line 67, in __init__
    super().__init__(id, *args, **kwargs)
TypeError: BaseProvider.__init__() got an unexpected keyword argument 'ssl_verify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/octodns/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns/cmds/sync.py", line 56, in main
    manager = Manager(args.config_file)
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns/manager.py", line 128, in __init__
    self.providers = self._config_providers(providers_config)
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns/manager.py", line 202, in _config_providers
    raise ManagerException(
octodns.manager.ManagerException: Incorrect provider config for test-server01
```

Here is the relevant part of the config file:

```

providers:
  test-server01:
      class: octodns_powerdns.PowerDnsProvider
      # The host on which PowerDNS api is listening (required)
      host: test-server01.testdomain.com
      scheme: https
      # The port on which PowerDNS api is listening (optional, default 8081)
      port: 443
      ssl_verify: false
      # The api key that grans access (required, example is using an env var)
      api_key: foo-key


```

If I remove ssl_verify it stucks at verifying it, if I put it back it gives the error above.  I hope I made it clear enough. Thank you for the hardwork.

**Comment by callMe-Root** [comment]
So I tried something to resolve my own problem, looks like it works for me, I hope it will be helpful for you, too. If you consider a new release fixing this issue, you would save me from a burden of deploying it for dozens of environments

**Comment by yzguy** [comment]
You can follow the directions https://github.com/octodns/octodns-powerdns#shas to install the version from main (which has the new features to toggle ssl_verify)

You can also pull this in via `requirements.txt` (details [here](https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source))

**Comment by yzguy** [comment]
#45 added the `ssl_verify` argument to the provider.

You can pull this version in according to https://github.com/octodns/octodns-powerdns#shas to install the version from main or you can also pull this in via requirements.txt (details [here](https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source))

We'll get a release here soon, so then you can pin a specific version number instead of git SHA, but the directions are there if you to pull in the new version now.

**Comment by callMe-Root** [comment]
thank you for explanation, I didn't consider the latest release is behind the master :D so I confused when I checked the readme
